version: "3.3"
services:
  db:
    container_name: postgraphile_template_db
    image: postgraphile_template_db
    restart: always
    build: ./db
    volumes:
      - ./db/data:/var/lib/postgresql/data
    env_file:
      - ./db/.env
    networks:
      - network
    ports:
      - 5432:5432
  
  api:
    container_name: postgraphile_template_api
    image: postgraphile_template_api
    restart: always
    build: ./api
    volumes:
      - ./api/server:/app/server
    env_file:
      - ./api/.env
    depends_on:
      - db
    networks:
      - network
    ports:
      - 5433:5433
    #command: ["--connection", "${DATABASE_URL}", "--port", "5433", "--schema", "public", "--append-plugins", "postgraphile-plugin-connection-filter"]

networks:
  network: