version: "3.3"
services:
  db:
    container_name: postgraphile_template_db
    image: postgraphile_template_db
    restart: always
    build: ./db
    env_file:
      - ./.env
    volumes:
      - ./db/data:/var/lib/postgresql/data
    networks:
      - network
    ports:
      - 5432:5432
  
  api:
    container_name: postgraphile_template_api
    image: postgraphile_template_api
    restart: always
    build: 
      context: ./api
      dockerfile: Dockerfile.dev
    volumes:
      - ./api/server:/app/server
    env_file:
      - ./.env
    depends_on:
      - db
    networks:
      - network
    ports:
      - 5433:5433
    #command: ["--connection", "${DATABASE_URL}", "--port", "5433", "--schema", "public", "--append-plugins", "postgraphile-plugin-connection-filter"]

  web:
    container_name: postgraphile_template_web
    image: postgraphile_template_web
    build:
      context: ./web
      dockerfile: Dockerfile.dev
    volumes:
      - ./web:/app
    env_file:
      - ./.env
    depends_on:
      - api
    networks:
      - network
    ports:
      - 5434:5173

networks:
  network: