version: "3.3"
services:
  db:
    container_name: forum-example-db
    restart: always
    image: forum-example-db
    build:
      context: ./db
    volumes:
      - ./db/data:/var/lib/postgresql/data
    env_file:
      - ./.env
    networks:
      - network
    ports:
      - 5432:5432
  
  graphql:
    container_name: forum-example-graphql
    restart: always
    image: forum-example-graphql
    build:
      context: ./graphql
    volumes:
      - ../../server:/app/server
    env_file:
      - ./.env
    depends_on:
      - db
    networks:
      - network
    ports:
      - 5433:5433
    #command: ["--connection", "${DATABASE_URL}", "--port", "5433", "--schema", "public", "--append-plugins", "postgraphile-plugin-connection-filter"]

networks:
  network: